### ISSUE TITLE
timeit

### ISSUE THREAD

**Issue by stefangeorge** [Anaconda-Server/support#3]
I cannot find this package
https://docs.python.org/2/library/timeit.html
 in the anaconda distro even though it seems from the above link that it should be in the standard python distro. I tried
`conda install timeit`
and get

    Fetching package metadata: ....

    Error: No packages found in current linux-64 channels matching: timeit

    You can search for this package on anaconda.org with

    anaconda search -t conda timeit

```
~/Documents$ anaconda search -t conda bettertimeit
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
No packages found
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
Found 0 packages
```

Any suggestions?

**Comment by stephenakearns** [comment]
Hi @stefangeorge - not currently supported in the Anaconda Distro - @csoja  what is the process for nominating packages to be included in the distro?

**Comment by stephenakearns** [comment]
Hi @stefangeorge I spoke with @csoja and there isn't a formal process currently for nominating packages. The current method would be to log an issue on the Anaconda Repository: https://github.com/continuumio/anaconda-issues/issues and make your case for why it should be included in the Anaconda Distro. Have colleagues +1 the issue so that we can get community input on the priority.
